language: scala
scala:
   - 2.8.2
   - 2.9.2
   - 2.10.0
 jdk:
   - oraclejdk7
   - openjdk7
   - openjdk6
 
 notifications:
  email:
    recipients:
      - visenger@gmai.com
    on_failure: change
    
    
